In [1]:
import pandas as pd
import numpy as np

In [56]:
df=pd.read_csv(r"X:\CODING\Statistical Learning Lab\Assignemnt1\food_coded.csv")
df.head()

GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0    2.4       2          1               430           NaN           315.0   
1  3.654       1          1               610           3.0           420.0   
2    3.3       1          1               720           4.0           420.0   
3    3.2       1          1               430           3.0           420.0   
4    3.5       1          1               720           2.0           420.0   

   coffee                      comfort_food        comfort_food_reasons  \
0       1                              none       we dont have comfort    
1       2       chocolate, chips, ice cream        Stress, bored, anger   
2       2   frozen yogurt, pizza, fast food             stress, sadness   
3       2  Pizza, Mac and cheese, ice cream                     Boredom   
4       2      Ice cream, chocolate, chips   Stress, boredom, cravings    

   comfort_food_reasons_coded  ...  soup  sports  thai_food tortilla_calories  \
0                         9.0  ...   1.0     1.0          1            1165.0   
1                         1.0  ...   1.0     1.0          2             725.0   
2                         1.0  ...   1.0     2.0          5            1165.0   
3                         2.0  ...   1.0     2.0          5             725.0   
4                         1.0  ...   1.0     1.0          4             940.0   

   turkey_calories  type_sports veggies_day  vitamins  waffle_calories  \
0              345   car racing           5         1             1315   
1              690  Basketball            4         2              900   
2              500         none           5         1              900   
3              690          NaN           3         1             1315   
4              500     Softball           4         2              760   

                     weight  
0                       187  
1                       155  
2  I'm not answering this.   
3             Not sure, 240  
4                       190  

[5 rows x 61 columns]

In [57]:
print(f"number of observations:{df.shape[0]}")
print(f"number of variables:{df.shape[1]}")

number of observations:125
number of variables:61


In [58]:
print(df.dtypes)

GPA                  object
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...   
type_sports          object
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight               object
Length: 61, dtype: object


In [59]:
df.dtypes.value_counts()

int64      27
float64    20
object     14
Name: count, dtype: int64

In [60]:
df.select_dtypes(include="number").isnull().sum()

Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current_coded               0
drink                            2
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
fav_cuisine_coded                0
fav_food                         2
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
ideal_diet_coded                 0
income                           1
indian_food         

In [61]:
df.select_dtypes(include="number").isnull().sum().sum()

np.int64(99)

In [62]:
df.duplicated().sum()

np.int64(0)

In [63]:
df.select_dtypes(include="object").columns

Index(['GPA', 'comfort_food', 'comfort_food_reasons', 'diet_current',
       'eating_changes', 'father_profession', 'fav_cuisine', 'food_childhood',
       'healthy_meal', 'ideal_diet', 'meals_dinner_friend',
       'mother_profession', 'type_sports', 'weight'],
      dtype='object')

In [64]:
for col in df.select_dtypes(include='object').columns:
    temp=pd.to_numeric(df[col],errors='coerce')
    conversion_rate=temp.notna().mean()
    if(conversion_rate>=0.9):
        df[col]=temp
        print(f"converted {col} to numeric with conversion ratio: {conversion_rate}")
    else:
        print(f"failed to convert {col} to numeric with converstion ratio: {conversion_rate}")

converted GPA to numeric with conversion ratio: 0.96
failed to convert comfort_food to numeric with converstion ratio: 0.0
failed to convert comfort_food_reasons to numeric with converstion ratio: 0.0
failed to convert diet_current to numeric with converstion ratio: 0.0
failed to convert eating_changes to numeric with converstion ratio: 0.0
failed to convert father_profession to numeric with converstion ratio: 0.0
failed to convert fav_cuisine to numeric with converstion ratio: 0.0
failed to convert food_childhood to numeric with converstion ratio: 0.0
failed to convert healthy_meal to numeric with converstion ratio: 0.0
failed to convert ideal_diet to numeric with converstion ratio: 0.0
failed to convert meals_dinner_friend to numeric with converstion ratio: 0.0
failed to convert mother_profession to numeric with converstion ratio: 0.0
failed to convert type_sports to numeric with converstion ratio: 0.0
converted weight to numeric with conversion ratio: 0.96


In [65]:
for col in df.select_dtypes(include="number").columns:
    print(f"COLUMN: {col}")
    print(f"mean: {df[col].mean()}")
    print(f"median: {df[col].median()}")
    print(f"Variance: {df[col].var()}")
    print(f"Std: {df[col].std()}")
    print(f"quantiles: {df[col].quantile([0.25,0.50,0.75])}")
    print()

COLUMN: GPA
mean: 3.4155583333333337
median: 3.5
Variance: 0.15220838312324936
Std: 0.39013892797726474
quantiles: 0.25    3.2
0.50    3.5
0.75    3.7
Name: GPA, dtype: float64

COLUMN: Gender
mean: 1.392
median: 1.0
Variance: 0.24025806451612908
Std: 0.4901612637858372
quantiles: 0.25    1.0
0.50    1.0
0.75    2.0
Name: Gender, dtype: float64

COLUMN: breakfast
mean: 1.112
median: 1.0
Variance: 0.10025806451612906
Std: 0.3166355389341649
quantiles: 0.25    1.0
0.50    1.0
0.75    1.0
Name: breakfast, dtype: float64

COLUMN: calories_chicken
mean: 577.32
median: 610.0
Variance: 17217.154838709674
Std: 131.2141563959837
quantiles: 0.25    430.0
0.50    610.0
0.75    720.0
Name: calories_chicken, dtype: float64

COLUMN: calories_day
mean: 3.0283018867924527
median: 3.0
Variance: 0.40871518418688224
Std: 0.6393083639268943
quantiles: 0.25    3.0
0.50    3.0
0.75    3.0
Name: calories_day, dtype: float64

COLUMN: calories_scone
mean: 505.241935483871
median: 420.0
Variance: 53287.33936532

Std: 230.8405063357147
quantiles: 0.25    420.0
0.50    420.0
0.75    420.0
Name: calories_scone, dtype: float64

COLUMN: coffee
mean: 1.752
median: 2.0
Variance: 0.18799999999999997
Std: 0.43358966777357594
quantiles: 0.25    2.0
0.50    2.0
0.75    2.0
Name: coffee, dtype: float64

COLUMN: comfort_food_reasons_coded
mean: 2.69811320754717
median: 2.0
Variance: 3.8889487870619934
Std: 1.9720417812668152
quantiles: 0.25    2.0
0.50    2.0
0.75    3.0
Name: comfort_food_reasons_coded, dtype: float64

COLUMN: cook
mean: 2.7868852459016393
median: 3.0
Variance: 1.0781736892020048
Std: 1.038351428564532
quantiles: 0.25    2.0
0.50    3.0
0.75    3.0
Name: cook, dtype: float64

COLUMN: comfort_food_reasons_coded.1
mean: 2.688
median: 2.0
Variance: 3.6518709677419356
Std: 1.9109869093591236
quantiles: 0.25    2.0
0.50    2.0
0.75    3.0
Name: comfort_food_reasons_coded.1, dtype: float64

COLUMN: cuisine
mean: 1.3888888888888888
median: 1.0
Variance: 0.9501557632398754
Std: 0.9747593360619201

In [66]:
df.describe()

GPA      Gender   breakfast  calories_chicken  calories_day  \
count  120.000000  125.000000  125.000000        125.000000    106.000000   
mean     3.415558    1.392000    1.112000        577.320000      3.028302   
std      0.390139    0.490161    0.316636        131.214156      0.639308   
min      2.200000    1.000000    1.000000        265.000000      2.000000   
25%      3.200000    1.000000    1.000000        430.000000      3.000000   
50%      3.500000    1.000000    1.000000        610.000000      3.000000   
75%      3.700000    2.000000    1.000000        720.000000      3.000000   
max      4.000000    2.000000    2.000000        720.000000      4.000000   

       calories_scone     coffee  comfort_food_reasons_coded        cook  \
count      124.000000  125.00000                  106.000000  122.000000   
mean       505.241935    1.75200                    2.698113    2.786885   
std        230.840506    0.43359                    1.972042    1.038351   
min        315.000000    1.00000                    1.000000    1.000000   
25%        420.000000    2.00000                    2.000000    2.000000   
50%        420.000000    2.00000                    2.000000    3.000000   
75%        420.000000    2.00000                    3.000000    3.000000   
max        980.000000    2.00000                    9.000000    5.000000   

       comfort_food_reasons_coded.1  ...  self_perception_weight        soup  \
count                    125.000000  ...              124.000000  124.000000   
mean                       2.688000  ...                3.120968    1.217742   
std                        1.910987  ...                1.115980    0.414385   
min                        1.000000  ...                1.000000    1.000000   
25%                        2.000000  ...                2.000000    1.000000   
50%                        2.000000  ...                3.000000    1.000000   
75%                        3.000000  ...                4.000000    1.000000   
max                        9.000000  ...                6.000000    2.000000   

           sports   thai_food  tortilla_calories  turkey_calories  \
count  123.000000  125.000000         124.000000       125.000000   
mean     1.390244    3.336000         947.580645       555.040000   
std      0.489800    1.436528         202.090179       152.370379   
min      1.000000    1.000000         580.000000       345.000000   
25%      1.000000    2.000000         725.000000       500.000000   
50%      1.000000    3.000000         940.000000       500.000000   
75%      2.000000    5.000000        1165.000000       690.000000   
max      2.000000    5.000000        1165.000000       850.000000   

       veggies_day    vitamins  waffle_calories      weight  
count   125.000000  125.000000       125.000000  120.000000  
mean      4.008000    1.512000      1073.400000  158.500000  
std       1.081337    0.501867       248.667092   31.758278  
min       1.000000    1.000000       575.000000  100.000000  
25%       3.000000    1.000000       900.000000  135.000000  
50%       4.000000    2.000000       900.000000  155.000000  
75%       5.000000    2.000000      1315.000000  180.000000  
max       5.000000    2.000000      1315.000000  265.000000  

[8 rows x 49 columns]

In [67]:
df['calories_day'].unique()

array([nan,  3.,  4.,  2.])

In [68]:
np.all(np.equal(df['calories_day'].dropna()%1,0))

np.True_

In [69]:
df.select_dtypes(include='number').columns

Index(['GPA', 'Gender', 'breakfast', 'calories_chicken', 'calories_day',
       'calories_scone', 'coffee', 'comfort_food_reasons_coded', 'cook',
       'comfort_food_reasons_coded.1', 'cuisine', 'diet_current_coded',
       'drink', 'eating_changes_coded', 'eating_changes_coded1', 'eating_out',
       'employment', 'ethnic_food', 'exercise', 'father_education',
       'fav_cuisine_coded', 'fav_food', 'fries', 'fruit_day', 'grade_level',
       'greek_food', 'healthy_feeling', 'ideal_diet_coded', 'income',
       'indian_food', 'italian_food', 'life_rewarding', 'marital_status',
       'mother_education', 'nutritional_check', 'on_off_campus',
       'parents_cook', 'pay_meal_out', 'persian_food',
       'self_perception_weight', 'soup', 'sports', 'thai_food',
       'tortilla_calories', 'turkey_calories', 'veggies_day', 'vitamins',
       'waffle_calories', 'weight'],
      dtype='object')

In [70]:
for col in df.select_dtypes(include='number').columns:
    if np.all(np.equal(df[col].dropna()%1,0)):
        avg=round(df[col].mean())
        df[col]=df[col].fillna(avg)
    else:
        avg=df[col].mean()
        df[col]=df[col].fillna(avg)

In [71]:
for col in df.columns:
    na=df[col].isna().sum()
    if na>0:
        print(f"{col} has {na} missing")

comfort_food has 1 missing
comfort_food_reasons has 2 missing
diet_current has 1 missing
eating_changes has 3 missing
father_profession has 3 missing
fav_cuisine has 2 missing
food_childhood has 1 missing
healthy_meal has 1 missing
ideal_diet has 1 missing
meals_dinner_friend has 3 missing
mother_profession has 2 missing
type_sports has 26 missing


In [72]:
for col in df.select_dtypes(include='object').columns:
    df[col]=df[col].fillna('missing')

In [73]:
for col in df.columns:
    if "food" in col:
        print(col)

comfort_food
comfort_food_reasons
comfort_food_reasons_coded
comfort_food_reasons_coded.1
ethnic_food
fav_food
food_childhood
greek_food
indian_food
italian_food
persian_food
thai_food


In [75]:
for col in df.columns:
    if "cal" in col:
        print(col)

calories_chicken
calories_day
calories_scone
tortilla_calories
turkey_calories
waffle_calories


In [77]:
df['indian_food'].unique()

array([5, 4, 2, 1, 3])

In [78]:
df['italian_food'].unique()

array([5, 4, 3])

In [79]:
df['thai_food'].unique()

array([1, 2, 5, 4, 3])

In [80]:
df['greek_food'].unique()

array([5, 4, 2, 3, 1])

In [81]:
df['persian_food'].unique()

array([5., 4., 2., 1., 3.])

In [83]:
for col in df.columns:
    if 'food' in col:
        print(col)
        print(df[col].dtypes)
        print()

comfort_food
object

comfort_food_reasons
object

comfort_food_reasons_coded
float64

comfort_food_reasons_coded.1
int64

ethnic_food
int64

fav_food
float64

food_childhood
object

greek_food
int64

indian_food
int64

italian_food
int64

persian_food
float64

thai_food
int64

